# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        openapi: 3.0.0
        info:
            title: Immofix API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
