services:
    _defaults:
        autowire: true
        autoconfigure: true

    # On configure explicitement ton MailService
    App\Services\MailService:
        arguments:
            $apiKey: '%env(string:MAILJET_API_KEY)%'
            $apiSecret: '%env(string:MAILJET_API_SECRET)%'
            $fromEmail: '%env(string:MAILJET_FROM_EMAIL)%'
            $fromName: '%env(string:MAILJET_FROM_NAME)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
